travis:
  secure:
    BINSTAR_TOKEN: JKd2gK3bI8hu7X6QjMTIua4J7OVFPQiuXt1Se0n43GbkIyf5TgwTdrvMb3+cKjqn3kH5WsHPU3UrHb4wnGrapUOZd+xEOPw4aC7aHyeQzGvLxnmo5gKYyVo/snztQlndWzWZjnY42DCiSw96A1RFDJcqhEqZUJnnC63uYWCPdDCXsTIECO4Dr5omKOOq8528G6regrWBI4EBHFP+gv6FoG7oxLXAzoTmcA1EELEMUVqc7JahDxdFyImhN1tJRsh1iafp7Lc0DVqU2Tuc38rLeYlo8E9seHCPgABk/IedQRCQ7Vr1+X3WGjfBufg3N1KnVl/TzVMrZUpxciF37ktH0dR2mTGOcv7tRpKBZTCbLJR6ji8UuyVcXhsRg9s5Lv8ahn1v6gUxhYenw87SI5XEyPgbJQrMP1Jbb2EgJvRAcjRnWDjmhohbTXHEUPLMmelNVOwvCqfck0v5BTlqBu8DiWSIbBMyxntv5NoZHYwgQnL95X3y2KXIZtBAFKY/2YcL1DubSf87kbYtvt54uPX+IqYhR9KvRJ7+AM1ZelLFbUMjSiL4rthb84fKWKloPNgpjQYOKLPJ980W2iBFnZW+NLnNn0cjpLGghurCDwncm5M/d6QdW9F02gdplflU5MqfTP2cZnX9IGDBn2mxFxcUon1W/1KEwWGGFlYTyRK2/R4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
